### ISSUE TITLE
Resumption as a spec?

### ISSUE THREAD

**Issue by Borwe** [ElarianLtd/sdk-spec#1]
I am confused, from the docs, there is no resumption support in rsocket implementations in Java and most, yet Elarian has a java-sdk... Is it realy a requirement?

[rsocket-implementations](https://rsocket.io/about/implementations)

**Comment by aksalj** [comment]
Hey @Borwe, resumption is a requirement for some of the new features we will be releasing over the coming months. That being said, the rsocket support matrix is a little out of date, [rsocket-java](https://github.com/rsocket/rsocket-java) supports resumption already.
